### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by dunphyben** [FrontierSF/Frontier-Conf#25]
Currently the metadata shows as:

![Screenshot of the Google search results for FrontierSF](https://user-images.githubusercontent.com/5455826/33563921-3506e65c-d8e7-11e7-83c2-68595b21d0bf.png)
Let's update this to

`A week of events for learning basic and advanced blockchain development. Conference, hackathon, workshops, hiring mixer. San Francisco, March 2018.`

Kyle answers how to add metadata to a Gatsby site here https://github.com/gatsbyjs/gatsby/issues/266

**Comment by dunphyben** [comment]
What we're getting from google:

![image](https://user-images.githubusercontent.com/5455826/33860874-b23189ea-de8f-11e7-9498-c83188e64e19.png)

I'm trying to get Google to recrawl the site to see if that's the issue, but I'm having trouble finding out where that is. Their redesign is a nightmare and [this article](https://support.google.com/webmasters/answer/6065812) is no help. Those instructions lead to a dead end. 

In any case, the tile should be `Frontier: Blockchain Developer Conference` not "Conference"

**Comment by prashanthr** [comment]
That looks so messed up on Google. I have no idea how it picks up
"conference" when the title clearly says otherwise because I know we have
set the metadata correctly.

I'll take another look, update the title, add extra metadata if necessary,
update the alt text for images, and try to set it up to be crawled again.

**Comment by dunphyben** [comment]
Turns out it was indeed a recrawl issue. I finally found the google link, it's [here](https://www.google.com/webmasters/tools/submit-url?hl=en&mesd=AB9YKzKhm85UXyQ4oLaVsVJBlRoDPR20DTMYZXjARBtMKZqKTidjW2Tm-UQi48ZRyaIKWROuTJzOF5INcvRqPAzkmApWGJQTVrYOOfw5o63oJA5W3-E9z9Cq-iqiAtJkb8r71qlUuuAt&pli=1) for future reference.

**Comment by prashanthr** [comment]
Awesome. Good to hear. I was about to start messing with google bot configs.
